### PR TITLE
Update log file path to generic %appdata%

### PR DESCRIPTION
**Pull request by DarrenSchwartz**
Use AHK's %A_AppData% variable instead of manually editing the log path for each user.

### CODE REVIEW

**Review by RobertCSternberg — APPROVED** [review]

**Comment by RobertCSternberg** [comment]
I have tested this change successfully.

**Review by DarrenSchwartz — COMMENTED** [review]
Looks good. Should it be merged?

**Comment by RobertCSternberg** [comment]
The "new" teams no longer uses the log path specified (or does not follow the syntax of the prior version. Until this is addressed only the "legacy" version of teams is supported.

**Comment by ajobbins** [comment]
I've merged the pull request, but as mentioned the "new" teams has changed.
The path forward is probably to try and pull something using the local API, but I haven't looked into this. I'm currently using the MS Graph API as I now have the ability to set this up in my corporate environment.

**Pull request merged**
